import{i as a,a as L,S}from"./assets/vendor-89feecc5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const m=document.querySelector(".form"),d=document.querySelector(".gallery"),q=document.querySelector("div"),v=document.querySelector("input"),u=document.querySelector(".btn-load"),h=()=>{const e=document.createElement("span");e.classList.add("loader"),q.append(e)},i=()=>{const e=document.querySelector(".loader");e&&e.remove()},I=()=>{u.style.display="block"},l=()=>{u.style.display="none"};let p=1,y=40,f=" ",g;m.addEventListener("submit",async e=>{p=1,h(),d.innerHTML=" ",e.preventDefault();try{f=v.value;const o=await b();w(o),m.reset(),i(),I(),o.hits.length<40&&l(),o.hits.length===0&&(l(),a.error({message:"Sorry, there are no images matching <br>your search query. Please try again!</br>",position:"center",transitionIn:"fadeInLeft"}))}catch{a.error({title:"Error"})}});u.addEventListener("click",async()=>{h();try{p+=1;const e=await b();w(e),i();const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),(d.children.length>=g||e.hits.length<y)&&(a.warning({message:"We are sorry, but you have reached the end of search results.",position:"bottomCenter",transitionIn:"fadeInDown"}),l())}catch{a.error({title:"Error"}),i()}});async function b(){try{const e="41764579-b97d65b31c0abd4efd9d4830e",o=new URLSearchParams({key:e,q:f,image_type:"photo",orientation:"horizontal",safesearch:!0,page:p,per_page:y}),s=await L.get(`https://pixabay.com/api/?${o}`);return g=s.data.totalHits,s.data}catch(e){throw console.log(e),WebTransportError}}function w(e){const o=e.hits.map(n=>`
            <li class="gallery-item"><a href="${n.largeImageURL}">
          <img class="gallery-image" src="${n.webformatURL}" alt="${n.tags}"></a>
          <p><b>Likes: </b>${n.likes}</p>
          <p><b>Views: </b>${n.views}</p>
          <p><b>Comments: </b>${n.comments}</p>
          <p><b>Downloads: </b>${n.downloads}</p>
          </li>`).join("");d.insertAdjacentHTML("beforeend",o),new S(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}).on("show.simplelightbox").refresh(),i()}
//# sourceMappingURL=commonHelpers.js.map
