import{i as m,a as b,S as w}from"./assets/vendor-89feecc5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerpolicy&&(n.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?n.credentials="include":t.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const u=document.querySelector(".form"),c=document.querySelector(".gallery"),L=document.querySelector("div"),S=document.querySelector("input"),l=document.querySelector(".btn-load"),f=()=>{const e=document.createElement("span");e.classList.add("loader"),L.append(e)},a=()=>{const e=document.querySelector(".loader");e&&e.remove()},v=()=>{l.style.display="block"},h=()=>{l.style.display="none"};let d=1,q=40,p;u.addEventListener("submit",async e=>{f(),c.innerHTML=" ",e.preventDefault(),d+=1;try{const o=await y();g(o),u.reset(),a(),v(),o.hits.length===0&&(m.error({message:"Sorry, there are no images matching <br>your search query. Please try again!</br>",position:"center",transitionIn:"fadeInLeft"}),a())}catch(o){console.log(o),h()}});l.addEventListener("click",async()=>{f();try{d+=1;const e=await y();g(e),a();const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),c.children.length===e.totalHits&&(m.warning({message:"We are sorry, but you have reached the end of search results.",position:"bottomCenter",transitionIn:"fadeInDown"}),h())}catch(e){console.log(e),a()}});async function y(){const e=S.value,o="41764579-b97d65b31c0abd4efd9d4830e",r=new URLSearchParams({key:o,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:d,per_page:q}),s=await b.get(`https://pixabay.com/api/?${r}`);return s.data.totalHits,s.data}function g(e){const o=e.hits.map(r=>`
            <li class="gallery-item"><a href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}"></a>
          <p><b>Likes: </b>${r.likes}</p>
          <p><b>Views: </b>${r.views}</p>
          <p><b>Comments: </b>${r.comments}</p>
          <p><b>Downloads: </b>${r.downloads}</p>
          </li>`).join("");c.insertAdjacentHTML("beforeend",o),p=new w(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}),p.on("show.simplelightbox").refresh(),a()}
//# sourceMappingURL=commonHelpers.js.map
